# Generated by Django 5.2.7 on 2026-03-03 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MAIN', '0007_customer_gender_vendor_warrantyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack_Size_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(choices=[('small', 'Small Pack'), ('medium', 'Medium Pack'), ('large', 'Large Pack')], max_length=20, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_capacity', models.PositiveIntegerField(help_text='Max items this pack can hold')),
            ],
        ),
        migrations.CreateModel(
            name='Section_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('availability_status', models.BooleanField(default=True)),
                ('requires_pack', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='University_Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luxa_crave.pack_size_config')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Pack_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='luxa_crave.order_pack')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='luxa_crave.section_product')),
            ],
        ),
        migrations.CreateModel(
            name='University_Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Ordering Mode', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.customer')),
                ('master_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_order', to='MAIN.masterorder')),
            ],
        ),
        migrations.AddField(
            model_name='order_pack',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='luxa_crave.university_order'),
        ),
        migrations.CreateModel(
            name='University_Outlet_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxa_crave.university_outlet')),
            ],
        ),
        migrations.AddField(
            model_name='section_product',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='luxa_crave.university_outlet_section'),
        ),
        migrations.AddField(
            model_name='university_outlet',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxa_crave.university_profile'),
        ),
        migrations.CreateModel(
            name='Crave_Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crave_profile', to='MAIN.customer')),
                ('default_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luxa_crave.university_profile')),
            ],
        ),
    ]
