# Generated by Django 5.2.7 on 2026-03-04 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0008_customer_university_profile'),
        ('luxa_crave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Venture_Profile_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_theme', models.CharField(default='standard_light', max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxa_crave.university_profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.customer')),
            ],
            options={
                'verbose_name': 'User Venture Profile Setting',
                'unique_together': {('user', 'profile')},
            },
        ),
    ]
