# Generated by Django 5.2.7 on 2026-03-04 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0002_user_venture_profile_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_outlet',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='university_outlet_section',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='luxa_crave.university_outlet'),
        ),
    ]
