# Generated by Django 5.2.7 on 2026-03-04 23:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0002_user_venture_profile_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack_size_config',
            name='max_overflow',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Absolute limit including nylons', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section_product',
            name='filling_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text="The internal 'volume' this item takes (e.g. 0.5 for rice, 1.5 for chicken)", max_digits=5),
        ),
        migrations.AlterField(
            model_name='section_product',
            name='requires_pack',
            field=models.BooleanField(default=True),
        ),
    ]
