# Generated by Django 5.2.7 on 2026-03-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0003_university_outlet_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_product',
            name='comes_with_pack',
            field=models.BooleanField(default=False),
        ),
    ]
