# Generated by Django 5.2.7 on 2026-03-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0004_section_product_comes_with_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
