# Generated by Django 5.2.7 on 2026-03-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0005_section_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack_size_config',
            name='pack_image',
            field=models.ImageField(blank=True, null=True, upload_to='pack_images/'),
        ),
    ]
