# Generated by Django 5.2.7 on 2026-03-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0006_pack_size_config_pack_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_product',
            name='need_soup',
            field=models.BooleanField(default=False),
        ),
    ]
