# Generated by Django 5.2.7 on 2026-03-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0007_section_product_need_soup'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_product',
            name='not_ordered_alone',
            field=models.BooleanField(default=False),
        ),
    ]
