# Generated by Django 5.2.7 on 2026-03-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0003_pack_size_config_max_overflow_and_more'),
        ('luxa_crave', '0008_section_product_not_ordered_alone'),
    ]

    operations = [
    ]
