# Generated by Django 5.2.7 on 2026-03-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0009_merge_20260305_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_pack',
            name='multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
