# Generated by Django 5.2.7 on 2026-03-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0010_order_pack_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_product',
            name='is_a_soup',
            field=models.BooleanField(default=False),
        ),
    ]
