# Generated by Django 5.2.7 on 2026-03-09 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0011_section_product_is_a_soup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university_order',
            name='master_order',
        ),
        migrations.AddField(
            model_name='university_order',
            name='building_block',
            field=models.CharField(blank=True, help_text='e.g., Block G, West Wing', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='university_order',
            name='order_number',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='university_order',
            name='room_number',
            field=models.CharField(blank=True, help_text='e.g., Room 405', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='university_order',
            name='terminal_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university_profile',
            name='profile_id',
            field=models.CharField(editable=False, help_text='Unique identifier for campus routing (e.g., CAMPUS-XXXX)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='university_order',
            name='status',
            field=models.CharField(choices=[('ordering_mode', 'Ordering Mode'), ('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='ordering_mode', max_length=50),
        ),
        migrations.CreateModel(
            name='Campus_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_locations', to='luxa_crave.university_profile')),
            ],
        ),
        migrations.AddField(
            model_name='university_order',
            name='location_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luxa_crave.campus_location'),
        ),
        migrations.CreateModel(
            name='Location_Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='luxa_crave.campus_location')),
            ],
        ),
        migrations.AddField(
            model_name='university_order',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luxa_crave.location_building'),
        ),
    ]
