# Generated by Django 5.2.7 on 2026-03-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0012_remove_university_order_master_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crave_student_profile',
            name='campus_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luxa_crave.campus_location'),
        ),
        migrations.CreateModel(
            name='Default_Proxy_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('proxy_address', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_proxy', to='luxa_crave.crave_student_profile')),
                ('proxy_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luxa_crave.location_building')),
                ('proxy_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luxa_crave.campus_location')),
            ],
        ),
    ]
