# Generated by Django 5.2.7 on 2026-03-09 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0013_crave_student_profile_campus_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_proxy_settings',
            name='proxy_photo',
            field=models.ImageField(blank=True, null=True, upload_to='proxy_photos/'),
        ),
        migrations.AlterField(
            model_name='default_proxy_settings',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_proxy', to='luxa_crave.crave_student_profile'),
        ),
    ]
