# Generated by Django 5.2.7 on 2026-03-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0014_default_proxy_settings_proxy_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crave_student_profile',
            name='proxy_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
