# Generated by Django 5.2.7 on 2026-03-09 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0015_crave_student_profile_proxy_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='crave_student_profile',
            name='campus_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luxa_crave.location_building'),
        ),
        migrations.AddField(
            model_name='crave_student_profile',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Campus_Pack_Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_name', models.CharField(help_text="e.g., 'My Friday Lunch', 'Post-Exam Feast'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='luxa_crave.crave_student_profile')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_presets', to='luxa_crave.university_outlet')),
                ('pack_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luxa_crave.pack_size_config')),
            ],
        ),
        migrations.CreateModel(
            name='Campus_Pack_Preset_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='luxa_crave.campus_pack_preset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxa_crave.section_product')),
            ],
        ),
    ]
