# Generated by Django 5.2.7 on 2026-03-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0016_crave_student_profile_campus_building_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Order_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Engine_Use_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='default_proxy_settings',
            name='proxy_seed_phrase_hash',
            field=models.CharField(blank=True, help_text='Hashed seed phrase for proxy authentication.', max_length=255, null=True),
        ),
    ]
