# Generated by Django 5.2.7 on 2026-03-10 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0017_customer_order_view_engine_use_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order_view',
            name='raw_order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_view', to='luxa_crave.university_order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_order_view',
            name='readable_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='engine_use_model',
            name='engine_payload',
            field=models.JSONField(default=1, editable=False, help_text='Machine-optimized JSON for the Engine App.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine_use_model',
            name='raw_order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='engine_view', to='luxa_crave.university_order'),
            preserve_default=False,
        ),
    ]
