# Generated by Django 5.2.7 on 2026-03-11 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0018_customer_order_view_raw_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engine_Use_Model',
            new_name='Campus_Engine_Order',
        ),
    ]
