# Generated by Django 5.2.7 on 2026-03-11 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0005_remove_courier_courier_profile_choices_and_more'),
        ('luxa_crave', '0019_rename_engine_use_model_campus_engine_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus_engine_order',
            name='assigned_campus_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_campus_orders', to='couriers.courier'),
        ),
    ]
