# Generated by Django 5.2.7 on 2026-03-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0020_campus_engine_order_assigned_campus_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_outlet',
            name='time_closed',
            field=models.TimeField(blank=True, help_text='e.g., 20:00:00', null=True),
        ),
        migrations.AddField(
            model_name='university_outlet',
            name='time_open',
            field=models.TimeField(blank=True, help_text='e.g., 08:00:00', null=True),
        ),
    ]
