# Generated by Django 5.2.7 on 2026-03-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0021_university_outlet_time_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_order',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
