# Generated by Django 5.2.7 on 2026-03-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0022_university_order_extra_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university_order',
            old_name='id',
            new_name='order_id',
        ),
    ]
