# Generated by Django 5.2.7 on 2026-03-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0023_rename_id_university_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_order',
            name='status',
            field=models.CharField(choices=[('ordering_mode', 'Ordering Mode'), ('pending', 'Pending'), ('processing', 'Processing'), ('assigned', 'Assigned'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='ordering_mode', max_length=50),
        ),
    ]
