# Generated by Django 5.2.7 on 2026-03-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0006_campusdump'),
        ('luxa_crave', '0023_rename_id_university_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus_engine_order',
            name='status',
            field=models.CharField(choices=[('forming', 'Forming'), ('assigned', 'Assigned'), ('shipped', 'In Transit'), ('completed', 'Completed'), ('pending_cancellation', 'Pending Cancellation')], default='forming', help_text='Status of the order in relation to the courier assignment.', max_length=30),
        ),
        migrations.AddField(
            model_name='university_order',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_orders', to='couriers.deliverybatch'),
        ),
    ]
