# Generated by Django 5.2.7 on 2026-03-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0024_campus_engine_order_status_university_order_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_order',
            name='total_physical_packs_db',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
