# Generated by Django 5.2.7 on 2026-03-14 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0025_university_order_total_physical_packs_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_profile',
            name='campus_call_sign',
            field=models.CharField(blank=True, help_text="Short code for logic routing (e.g., 'landmark_uni'). No spaces or caps allowed.", max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Call sign must be lowercase, contain no spaces, and only use letters, numbers, or underscores.', regex='^[a-z0-9_]+$')]),
        ),
    ]
