# Generated by Django 5.2.7 on 2026-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0026_university_profile_campus_call_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus_location',
            name='value',
            field=models.CharField(default='none', help_text="The exact 'location_category' value that will be used in the frontend", max_length=100),
        ),
        migrations.AddField(
            model_name='location_building',
            name='value',
            field=models.CharField(default='none', help_text="The exact 'building' value that will be used in the frontend", max_length=100),
        ),
        migrations.AlterField(
            model_name='location_building',
            name='name',
            field=models.CharField(help_text='The building name to be used in the strategy logic.', max_length=100),
        ),
    ]
