# Generated by Django 5.2.7 on 2026-03-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0027_campus_location_value_location_building_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus_engine_order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('assigned', 'Assigned'), ('dumped', 'Dumped'), ('failed', 'Failed')], default='pending', help_text='Status of the order in relation to the courier assignment.', max_length=30),
        ),
    ]
