# Generated by Django 5.2.7 on 2026-03-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0028_alter_campus_engine_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus_engine_order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('assigned', 'Assigned'), ('shiped', 'In Transit'), ('completed', 'Completed'), ('pending_cancellation', 'Pending Cancellation'), ('dumped', 'Dumped'), ('failed', 'Failed')], default='pending', help_text='Status of the order in relation to the courier assignment.', max_length=30),
        ),
    ]
