# Generated by Django 5.2.7 on 2026-03-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0024_alter_university_order_status'),
        ('luxa_crave', '0028_alter_campus_engine_order_status'),
    ]

    operations = [
    ]
