# Generated by Django 5.2.7 on 2026-03-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0029_alter_campus_engine_order_status'),
        ('luxa_crave', '0029_merge_20260316_1200'),
    ]

    operations = [
    ]
