# Generated by Django 5.2.7 on 2026-03-18 21:35

import luxa_crave.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0030_merge_20260316_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profiles/', validators=[luxa_crave.models.validate_photo_file, luxa_crave.models.validate_photo_size]),
        ),
    ]
