# Generated by Django 5.2.7 on 2026-03-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0030_merge_20260316_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_product',
            name='influence_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section_product',
            name='is_bread',
            field=models.BooleanField(default=False),
        ),
    ]
