# Generated by Django 5.2.7 on 2026-03-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0031_university_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_outlet',
            name='icon_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
