# Generated by Django 5.2.7 on 2026-03-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0031_section_product_influence_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_product',
            name='influence_value',
        ),
        migrations.AddField(
            model_name='pack_size_config',
            name='influence_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
