# Generated by Django 5.2.7 on 2026-03-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0032_remove_section_product_influence_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section_product',
            old_name='is_bread',
            new_name='is_strange',
        ),
        migrations.AddField(
            model_name='section_product',
            name='strange_value',
            field=models.CharField(blank=True, help_text="The exact 'strange_value' that will trigger validation pack validator .", max_length=255, null=True),
        ),
    ]
