# Generated by Django 5.2.7 on 2026-03-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0032_university_outlet_icon_url'),
        ('luxa_crave', '0033_rename_is_bread_section_product_is_strange_and_more'),
    ]

    operations = [
    ]
