# Generated by Django 5.2.7 on 2026-03-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0034_merge_20260319_0211'),
        ('luxa_crave', '0034_merge_20260319_1604'),
    ]

    operations = [
    ]
