# Generated by Django 5.2.7 on 2026-03-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0035_merge_20260319_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_pack',
            name='influence_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
