# Generated by Django 5.2.7 on 2026-03-19 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0036_order_pack_influence_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pack',
            name='pack_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='luxa_crave.pack_size_config'),
        ),
    ]
