# Generated by Django 5.2.7 on 2026-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0037_alter_order_pack_pack_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus_engine_order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('assigned', 'Assigned'), ('shipped', 'In Transit'), ('completed', 'Completed'), ('pending_cancellation', 'Pending Cancellation'), ('dumped', 'Dumped'), ('failed', 'Failed')], default='pending', help_text='Status of the order in relation to the courier assignment.', max_length=30),
        ),
    ]
