# Generated by Django 5.2.7 on 2026-03-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0038_alter_campus_engine_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_order',
            name='status',
            field=models.CharField(choices=[('ordering_mode', 'Ordering Mode'), ('pending', 'Pending'), ('processing', 'Processing'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='ordering_mode', max_length=50),
        ),
    ]
