# Generated by Django 5.2.7 on 2026-03-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0039_alter_university_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack_size_config',
            name='size_name',
            field=models.CharField(choices=[('loose', 'No Pack'), ('small', 'Small Pack'), ('medium', 'Medium Pack'), ('large', 'Large Pack')], max_length=20, unique=True),
        ),
    ]
