# Generated by Django 5.2.7 on 2026-03-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0040_alter_pack_size_config_size_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack_size_config',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
