# Generated by Django 5.2.7 on 2026-03-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0041_pack_size_config_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus_pack_preset',
            name='pack_multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
