# Generated by Django 5.2.7 on 2026-03-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0042_campus_pack_preset_pack_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_proxy_settings',
            name='proxy_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
    ]
