# Generated by Django 5.2.7 on 2026-03-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0043_default_proxy_settings_proxy_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_profile',
            name='on_break',
            field=models.BooleanField(default=False, help_text='Toggle to pause all orders for this university profile without taking it down completely.'),
        ),
    ]
