# Generated by Django 5.2.7 on 2026-03-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0044_university_profile_on_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_order',
            name='custom_assigned',
            field=models.BooleanField(default=False, help_text='True if the customer bypassed the engine to handpick a courier.'),
        ),
    ]
