# Generated by Django 5.2.7 on 2026-04-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0045_university_order_custom_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_product',
            name='has_charge',
            field=models.BooleanField(default=False, help_text='A way to know whether the product needs extra charges for fees'),
        ),
    ]
