# Generated by Django 5.2.7 on 2026-04-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0046_section_product_has_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_product',
            name='last_updated_availability',
            field=models.DateTimeField(auto_now=True, help_text='Updates every time the kitchen verifies stock.'),
        ),
        migrations.CreateModel(
            name='VerificationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('interceptor_message', models.TextField(blank=True, help_text='Mandatory if any item is out of stock.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_pings', to='luxa_crave.university_outlet')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationPingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('ping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_items', to='luxa_crave.verificationping')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxa_crave.section_product')),
            ],
        ),
    ]
