# Generated by Django 5.2.7 on 2026-04-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0047_section_product_last_updated_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_order',
            name='used_daily_promo',
            field=models.BooleanField(default=False),
        ),
    ]
