# Generated by Django 5.2.7 on 2026-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0048_university_order_used_daily_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_order',
            name='cancellation_reason_category',
            field=models.CharField(blank=True, choices=[('vendor_closed', 'Vendor is closed'), ('out_of_stock', 'Item out of stock'), ('massive_delay', 'Vendor delay too long'), ('bag_full', 'Bag capacity exceeded'), ('other', 'Other (See details)')], help_text='Fast-selection choice for the courier.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='university_order',
            name='cancellation_reason_details',
            field=models.TextField(blank=True, help_text="Mandatory text explanation if 'Other' is selected, or extra context.", null=True),
        ),
        migrations.AddField(
            model_name='university_order',
            name='is_advance_withdrawn',
            field=models.BooleanField(default=False, help_text='Phase 7: The Escrow Padlock. Locks the Escape Hatch when True.'),
        ),
        migrations.AddField(
            model_name='university_order',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='The Cryogenic Protocol. True if customer agreed to a massive vendor delay.'),
        ),
        migrations.AddField(
            model_name='university_order',
            name='ticked_at_outlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university_order',
            name='ticked_in_transit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university_order',
            name='ticked_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
