# Generated by Django 5.2.7 on 2026-04-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0049_university_order_cancellation_reason_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_order',
            name='wait_fee',
            field=models.BooleanField(default=False, help_text='True if ordered from BackYard Caf between 5:30 PM and 7:00 PM.'),
        ),
    ]
