# Generated by Django 5.2.7 on 2026-04-14 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0049_university_order_cancellation_reason_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_profile',
            name='weekday_close',
            field=models.TimeField(default=datetime.time(19, 0), help_text='e.g., 19:00:00 (7:00 PM)'),
        ),
        migrations.AddField(
            model_name='university_profile',
            name='weekday_open',
            field=models.TimeField(default=datetime.time(14, 0), help_text='e.g., 14:00:00 (2:00 PM)'),
        ),
        migrations.AddField(
            model_name='university_profile',
            name='weekend_close',
            field=models.TimeField(default=datetime.time(19, 0), help_text='e.g., 19:00:00 (7:00 PM)'),
        ),
        migrations.AddField(
            model_name='university_profile',
            name='weekend_open',
            field=models.TimeField(default=datetime.time(9, 0), help_text='e.g., 09:00:00 (9:00 AM)'),
        ),
    ]
