# Generated by Django 5.2.7 on 2026-04-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0050_university_profile_weekday_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus_engine_order',
            name='expected_eta_minutes',
            field=models.IntegerField(blank=True, help_text='The dynamically calculated minutes until delivery. Updated by the ACM Brain.', null=True),
        ),
    ]
