# Generated by Django 5.2.7 on 2026-04-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0050_university_order_wait_fee'),
        ('luxa_crave', '0051_campus_engine_order_expected_eta_minutes'),
    ]

    operations = [
    ]
