# Generated by Django 5.2.7 on 2026-04-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0052_merge_20260418_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus_engine_order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus_engine_order',
            name='in_transit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
