# Generated by Django 5.2.7 on 2026-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxa_crave', '0053_campus_engine_order_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus_engine_order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
