# Generated by Django 5.2.7 on 2026-01-31 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MAIN', '0001_initial'),
        ('couriers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='luxaorder',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='couriers.courier'),
        ),
        migrations.AddField(
            model_name='luxaorder',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='couriers.deliverybatch'),
        ),
        migrations.AddField(
            model_name='masterorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_orders', to='MAIN.customer'),
        ),
        migrations.AddField(
            model_name='luxaorder',
            name='order_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synchronized_order', to='MAIN.masterorder'),
        ),
        migrations.AddField(
            model_name='notification',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='MAIN.customer'),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Alert',
                'verbose_name_plural': 'Admin Alerts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('MAIN.notification',),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
            ],
            options={
                'verbose_name': 'User Message',
                'verbose_name_plural': 'User Messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('MAIN.notification',),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='MAIN.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='master_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='MAIN.masterorder'),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='MAIN.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MAIN.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='MAIN.category'),
        ),
        migrations.AddField(
            model_name='processedproductmedia',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_media', to='MAIN.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='MAIN.product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='MAIN.product'),
        ),
        migrations.AddField(
            model_name='draftorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='MAIN.product'),
        ),
        migrations.AddField(
            model_name='product3dtexture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textures_3d', to='MAIN.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='MAIN.product'),
        ),
        migrations.AddField(
            model_name='producttargetmesh',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_meshes', to='MAIN.product'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='target_mesh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='MAIN.producttargetmesh'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='mesh_color_source',
            field=models.OneToOneField(blank=True, help_text='If this variant was auto-generated from a 3D mesh color', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_variant', to='MAIN.productcolor'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='MAIN.product'),
        ),
        migrations.AddField(
            model_name='product3dtexture',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MAIN.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='MAIN.productvariant'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='MAIN.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='MAIN.product'),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='variant',
            field=models.ForeignKey(help_text='The variant (color, size, etc.) these images are associated with', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='MAIN.productvariant'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='MAIN.vendor'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='MAIN.vendor'),
        ),
        migrations.AddField(
            model_name='notification',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='MAIN.vendor'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='MAIN.customer'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='MAIN.product'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MAIN.wishlist'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='producttargetmesh',
            unique_together={('product', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('target_mesh', 'color_hex')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'variant_type'], name='MAIN_produc_product_bc2263_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_available'], name='MAIN_produc_product_37b9f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant_type', 'variant_value')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariantimage',
            unique_together={('product', 'variant')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product')},
        ),
    ]
