# Generated by Django 5.2.7 on 2026-02-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luxaorder',
            options={},
        ),
    ]
