# Generated by Django 5.2.7 on 2026-02-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_alter_luxaorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='document_back',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/back/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_front',
            field=models.FileField(upload_to='kyc_docs/front/'),
        ),
    ]
