# Generated by Django 5.2.7 on 2026-02-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_alter_kycverification_document_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_variants',
            field=models.JSONField(blank=True, help_text="Vendor-entered variants e.g {'Color': ['Red', 'Blue'], 'Size': ['S', 'M']}", null=True),
        ),
    ]
