# Generated by Django 5.2.7 on 2026-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_product_vendor_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='total_sales',
            field=models.PositiveIntegerField(default=0, help_text='Total number of completed sales. Admins can manually reset this to 0.'),
        ),
    ]
