# Generated by Django 5.2.7 on 2026-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_vendor_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='warrantyinfo',
            field=models.TextField(blank=True, help_text='Detailed warranty, refund, and return policy information.', null=True),
        ),
    ]
