# Generated by Django 5.2.7 on 2026-03-03 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0007_customer_gender_vendor_warrantyinfo'),
        ('luxa_crave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='university_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to='luxa_crave.university_profile'),
        ),
    ]
