# Generated by Django 5.2.7 on 2026-03-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0008_customer_university_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delivery_pin',
            field=models.CharField(blank=True, help_text='Secure PIN for delivery verification', max_length=128, null=True),
        ),
    ]
