# Generated by Django 5.2.7 on 2026-03-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0009_customer_delivery_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luxaorder',
            name='status',
            field=models.CharField(choices=[('pending_assignment', 'Pending Assignment'), ('assigned', 'Assigned'), ('shipped', 'In Transit'), ('completed', 'Completed'), ('pending_cancellation', 'Pending Cancellation')], default='forming', max_length=30),
        ),
    ]
