# Generated by Django 5.2.7 on 2026-03-15 16:03

import MAIN.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0009_customer_delivery_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='additional_addresses',
            field=models.JSONField(blank=True, default=list, help_text='Stores a list of extra address dictionaries'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Customer profile picture', null=True, upload_to='customer_profiles/', validators=[MAIN.models.validate_photo_size, MAIN.models.validate_photo_file]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, help_text='Vendor logo or profile image', null=True, upload_to='vendors/', validators=[MAIN.models.validate_photo_size, MAIN.models.validate_photo_file]),
        ),
    ]
