# Generated by Django 5.2.7 on 2026-03-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0010_customer_additional_addresses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='label',
            field=models.CharField(blank=True, help_text='Label for this address (e.g., Home, Work)', max_length=50, null=True),
        ),
    ]
