# Generated by Django 5.2.7 on 2026-03-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0010_alter_luxaorder_status'),
        ('MAIN', '0011_customer_label'),
    ]

    operations = [
    ]
