# Generated by Django 5.2.7 on 2026-03-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0013_merge_20260316_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luxaorder',
            name='status',
            field=models.CharField(choices=[('pending_assignment', 'Pending Assignment'), ('processing', 'Processing'), ('assigned', 'Assigned'), ('shipped', 'In Transit'), ('completed', 'Completed'), ('pending_cancellation', 'Pending Cancellation'), ('dumped', 'Dumped'), ('failed', 'Failed')], default='pending_assignment', max_length=30),
        ),
    ]
