# Generated by Django 5.2.7 on 2026-03-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0014_alter_luxaorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterorder',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterorder',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
