# Generated by Django 5.2.7 on 2026-03-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0015_masterorder_delivered_at_masterorder_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
    ]
