# Generated by Django 5.2.7 on 2026-03-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0017_alter_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='social_media_handle',
            field=models.CharField(blank=True, help_text='Your username on the selected social media platform (e.g., @yourhandle)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='social_media_platform',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook')], max_length=20, null=True),
        ),
    ]
