# Generated by Django 5.2.7 on 2026-03-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0018_kycverification_social_media_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='social_media_platform',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp')], max_length=20, null=True),
        ),
    ]
