# Generated by Django 5.2.7 on 2026-03-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0019_alter_kycverification_social_media_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='social_media_platform',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram')], max_length=20, null=True),
        ),
    ]
