# Generated by Django 5.2.7 on 2026-04-08 08:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0022_customer_social_media_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='promo_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage discount for this customer (e.g., 10.00 for 10% off). Admins can set this manually.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
