# Generated by Django 5.2.7 on 2026-04-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0023_customer_promo_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='promo_daily_counter',
            field=models.PositiveIntegerField(default=0, help_text='Tracks how many times the promo has been used today. Resets daily at midnight.'),
        ),
    ]
