# Generated by Django 5.2.7 on 2026-04-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0024_customer_promo_daily_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='promo_daily_total',
            field=models.PositiveIntegerField(default=0, help_text='Tracks the total discount amount given to this customer today.'),
        ),
    ]
