# Generated by Django 5.2.7 on 2026-04-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0025_customer_promo_daily_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_promo_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
