# Generated by Django 5.2.7 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0026_customer_last_promo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='promo_daily_total',
            field=models.PositiveIntegerField(default=0, help_text='The max number of courions the customer is allowed to use his discount on.'),
        ),
    ]
