# Generated by Django 5.2.7 on 2026-01-31 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MAIN', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDump',
            fields=[
            ],
            options={
                'verbose_name': 'Standard Dump Order',
                'verbose_name_plural': 'Standard Dump Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('MAIN.luxaorder',),
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_location', models.JSONField(blank=True, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('courier_category', models.CharField(choices=[('SAME_DAY', 'Same-Day Professional'), ('STANDARD', 'Standard Logistics')], default='STANDARD', max_length=20)),
                ('manual_key_required', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('batch_start_time', models.DateTimeField(blank=True, null=True)),
                ('last_delivery_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourierAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_access_key', models.CharField(max_length=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='couriers.courier')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CourierEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('last_location_update', models.DateTimeField(auto_now=True)),
                ('current_stop_load', models.PositiveIntegerField(default=0)),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engine', to='couriers.courier')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(default='forming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='couriers.courier')),
            ],
        ),
    ]
