# Generated by Django 5.2.7 on 2026-02-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
