# Generated by Django 5.2.7 on 2026-02-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_courier_is_busy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='last_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
