# Generated by Django 5.2.7 on 2026-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_alter_courier_last_delivery_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='courier_profile_choices',
            field=models.CharField(blank=True, choices=[('landmark_university', 'Landmark University')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier_category',
            field=models.CharField(choices=[('SAME_DAY', 'Same-Day Professional'), ('STANDARD', 'Standard Logistics'), ('STUDENT', 'Student Profile')], default='STANDARD', max_length=20),
        ),
    ]
