# Generated by Django 5.2.7 on 2026-03-11 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0004_courier_courier_profile_choices_courier_gender_and_more'),
        ('luxa_crave', '0019_rename_engine_use_model_campus_engine_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='courier_profile_choices',
        ),
        migrations.AddField(
            model_name='courier',
            name='courier_student_profile_choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luxa_crave.university_profile'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier_category',
            field=models.CharField(choices=[('SAME_DAY', 'Same-Day Professional'), ('STANDARD', 'Standard Logistics'), ('CAMPUS', 'Campus Profile')], default='STANDARD', max_length=20),
        ),
    ]
