# Generated by Django 5.2.7 on 2026-03-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0005_remove_courier_courier_profile_choices_and_more'),
        ('luxa_crave', '0023_rename_id_university_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusDump',
            fields=[
            ],
            options={
                'verbose_name': 'Campus Dump Order',
                'verbose_name_plural': 'Campus Dump Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('luxa_crave.university_order',),
        ),
    ]
