# Generated by Django 5.2.7 on 2026-03-15 16:03

import couriers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0005_remove_courier_courier_profile_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='courier_photos/', validators=[couriers.models.validate_photo_size, couriers.models.validate_photo_file]),
        ),
    ]
