# Generated by Django 5.2.7 on 2026-03-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0006_campusdump'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusBatch',
            fields=[
            ],
            options={
                'verbose_name': '🎒 Campus Delivery Batch',
                'verbose_name_plural': '🎒 Campus Delivery Batches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('couriers.deliverybatch',),
        ),
        migrations.CreateModel(
            name='CampusCourier',
            fields=[
            ],
            options={
                'verbose_name': '🎓 Campus Network Courier',
                'verbose_name_plural': '🎓 Campus Network Couriers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('couriers.courier',),
        ),
        migrations.CreateModel(
            name='StandardBatch',
            fields=[
            ],
            options={
                'verbose_name': '📦 Standard Delivery Batch',
                'verbose_name_plural': '📦 Standard Delivery Batches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('couriers.deliverybatch',),
        ),
        migrations.CreateModel(
            name='StandardCourier',
            fields=[
            ],
            options={
                'verbose_name': '👤 Standard Network Courier',
                'verbose_name_plural': '👤 Standard Network Couriers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('couriers.courier',),
        ),
    ]
