# Generated by Django 5.2.7 on 2026-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0007_campusbatch_campuscourier_standardbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='bag_location_tag',
            field=models.JSONField(blank=True, help_text="Metadata stamp copied directly from the order payload's delivery_point.", null=True),
        ),
    ]
