# Generated by Django 5.2.7 on 2026-03-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0008_deliverybatch_bag_location_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='total_volume',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
