# Generated by Django 5.2.7 on 2026-03-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0006_courier_photo'),
        ('couriers', '0009_deliverybatch_total_volume'),
    ]

    operations = [
    ]
