# Generated by Django 5.2.7 on 2026-03-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0010_merge_20260316_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_category',
            field=models.CharField(choices=[('SAME_DAY', 'Same-Day Professional'), ('STANDARD', 'Standard Logistics'), ('CAMPUS', 'Campus Profile')], default='CAMPUS', max_length=20),
        ),
    ]
