# Generated by Django 5.2.7 on 2026-03-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0011_alter_courier_courier_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
