# Generated by Django 5.2.7 on 2026-03-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0012_courier_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='custom_assigned',
            field=models.BooleanField(default=False, help_text='True if the customer bypassed the engine to handpick a courier.'),
        ),
    ]
