# Generated by Django 5.2.7 on 2026-03-31 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0013_courier_custom_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='custom_assigned',
        ),
    ]
