# Generated by Django 5.2.7 on 2026-04-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0014_remove_courier_custom_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='is_scouting',
            field=models.BooleanField(default=False),
        ),
    ]
