# Generated by Django 5.2.7 on 2026-04-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0015_courier_is_scouting'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='scouting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
