# Generated by Django 5.2.7 on 2026-04-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0016_courier_scouting_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_category',
            field=models.CharField(choices=[('SAME_DAY', 'Same-Day Professional'), ('STANDARD', 'Standard Logistics'), ('CAMPUS', 'Campus Profile'), ('CAMPUS_INTERCEPTOR', 'Campus Interceptor Profile')], default='CAMPUS', max_length=20),
        ),
    ]
