# Generated by Django 5.2.7 on 2026-04-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0017_alter_courier_courier_category'),
        ('luxa_crave', '0047_section_product_last_updated_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='interceptor_outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_outlet', to='luxa_crave.university_outlet'),
        ),
    ]
