# Generated by Django 5.2.7 on 2026-04-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0018_courier_interceptor_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_category',
            field=models.CharField(choices=[('SAME_DAY', 'Same-Day Professional'), ('STANDARD', 'Standard Logistics'), ('CAMPUS', 'Campus Profile'), ('CAMPUS_INTERCEPTOR', 'Campus Interceptor Profile'), ('EXTERNAL_UPDATER', 'External Updater Profile')], default='CAMPUS', max_length=20),
        ),
        migrations.CreateModel(
            name='CourierAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_admin_profile', to='couriers.courier')),
            ],
        ),
    ]
