# Generated by Django 5.2.7 on 2026-04-05 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0019_alter_courier_courier_category_courieradministrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUpdater',
            fields=[
            ],
            options={
                'verbose_name': '🔄 External Updater',
                'verbose_name_plural': '🔄 External Updaters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('couriers.courier',),
        ),
        migrations.AddField(
            model_name='courieradministrator',
            name='can_manage_disputes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courieradministrator',
            name='can_manage_escrow',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='courieradministrator',
            name='courier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='couriers.courier'),
        ),
    ]
