# Generated by Django 5.2.7 on 2026-04-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0020_externalupdater_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusInterceptor',
            fields=[
            ],
            options={
                'verbose_name': '🚆 Campus Interceptor',
                'verbose_name_plural': '🚆 Campus Interceptors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('couriers.courier',),
        ),
    ]
