# Generated by Django 5.2.7 on 2026-04-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0021_campusinterceptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
