# Generated by Django 5.2.7 on 2026-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0022_courier_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='active_shift_end',
            field=models.DateTimeField(blank=True, help_text='Triggers the 5-Minute Routing Blindspot before clock-out.', null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='courier_pocket',
            field=models.JSONField(blank=True, default=list, help_text='Temporary holding zone for scouted dumped orders awaiting the Tollbooth.'),
        ),
        migrations.AddField(
            model_name='courier',
            name='reliability_score',
            field=models.FloatField(default=100.0, help_text='The R-Score (0.0 to 100.0). Drops based on SLA failures.'),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='batch_efficiency',
            field=models.FloatField(blank=True, help_text='The calculated E_batch score applied at completion.', null=True),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='current_anchor',
            field=models.CharField(blank=True, help_text='The physically verified location based on the last Anchor Trigger.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='genesis_anchor',
            field=models.CharField(blank=True, help_text='The T=0 starting location declared by the courier.', max_length=100, null=True),
        ),
    ]
