# Generated by Django 5.2.7 on 2026-04-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0022_courier_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='social_media_handle',
            field=models.CharField(blank=True, help_text='Your username on the selected social media platform (e.g., @yourhandle)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='social_media_platform',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'Whatsapp')], max_length=20, null=True),
        ),
    ]
