# Generated by Django 5.2.7 on 2026-04-13 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0023_courier_active_shift_end_courier_courier_pocket_and_more'),
        ('couriers', '0023_courier_social_media_handle_and_more'),
    ]

    operations = [
    ]
