# Generated by Django 5.2.7 on 2026-04-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0024_merge_20260414_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='active_shift_start',
            field=models.DateTimeField(blank=True, help_text='Used to calculate the 15-minute grace period.', null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='consecutive_absences',
            field=models.IntegerField(default=0, help_text='Tracks consecutive days of missing shift grace periods.'),
        ),
        migrations.AddField(
            model_name='courier',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='True if they hit the 2-day strikeout or data falsification penalty.'),
        ),
        migrations.AddField(
            model_name='courier',
            name='last_heartbeat_ping',
            field=models.DateTimeField(blank=True, help_text='Updated every 30s by the frontend. Determines ALIVE/DEAD status.', null=True),
        ),
    ]
