# Generated by Django 5.2.7 on 2026-04-14 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0025_courier_active_shift_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier_Exemption_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(help_text='The specific day they cannot work.')),
                ('reason', models.TextField(help_text='Why are they missing the shift? (e.g., Exam, Illness)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='couriers.courier')),
            ],
            options={
                'unique_together': {('courier', 'target_date')},
            },
        ),
        migrations.CreateModel(
            name='Courier_Shift_Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_auto_snapped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='couriers.courier')),
            ],
            options={
                'ordering': ['-shift_date', 'start_time'],
                'unique_together': {('courier', 'shift_date', 'start_time')},
            },
        ),
    ]
