# Generated by Django 5.2.7 on 2026-04-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0026_courier_exemption_request_courier_shift_roster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier_shift_roster',
            options={'ordering': ['-shift_date', 'start_time'], 'verbose_name': 'Courier Shift Roster', 'verbose_name_plural': 'Courier Shift Rosters'},
        ),
    ]
