# Generated by Django 5.2.7 on 2026-04-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0027_alter_courier_shift_roster_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier_exemption_request',
            options={'verbose_name': 'Courier Exemption Request', 'verbose_name_plural': 'Courier Exemption Requests'},
        ),
    ]
