# Generated by Django 5.2.7 on 2026-04-16 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0028_alter_courier_exemption_request_options'),
        ('luxa_crave', '0050_university_profile_weekday_close_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired (Ghosted)')], default='pending', max_length=20)),
                ('sla_seconds', models.IntegerField(default=15, help_text='How many seconds the courier has to respond.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_pings', to='luxa_crave.campus_engine_order')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_pings', to='couriers.courier')),
            ],
        ),
    ]
