# Generated by Django 5.2.7 on 2026-04-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0029_manager_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='matrix_manifest',
            field=models.JSONField(blank=True, help_text="Stores the Brain's calculated pickup/drop-off sequence and micro ETAs.", null=True),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='total_eta_minutes',
            field=models.IntegerField(default=0, help_text='The master ETA for the entire batch.'),
        ),
    ]
