# Generated by Django 5.2.7 on 2026-04-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0030_deliverybatch_matrix_manifest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
