# Generated by Django 5.2.7 on 2026-04-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0031_deliverybatch_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
