# Generated by Django 5.2.7 on 2026-04-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0032_deliverybatch_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='is_immune',
            field=models.BooleanField(default=False, help_text='True if they are protected from auto-scouting due to a recent order dump or SLA failure.'),
        ),
    ]
