# Generated by Django 5.2.7 on 2026-04-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0033_courier_is_immune'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='2-Day Strikeout', max_length=255)),
            ],
        ),
    ]
