# Generated by Django 5.2.7 on 2026-04-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0034_bannedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier_shift_roster',
            name='minutes_online',
            field=models.FloatField(default=0.0, help_text='Stopwatch: Tracks actual minutes connected to the Engine during this specific shift block.'),
        ),
    ]
