# Generated by Django 5.2.7 on 2026-04-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0035_courier_shift_roster_minutes_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier_shift_roster',
            name='current_online_session_start',
            field=models.DateTimeField(blank=True, help_text="Records the exact timestamp when they toggle 'is_online' to True.", null=True),
        ),
    ]
