# Generated by Django 5.2.7 on 2026-04-22 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0037_remove_courier_shift_roster_current_online_session_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier_Telemetry_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_trigger', models.CharField(help_text="e.g., 'BATCH_COMPLETION', 'GHOST_PENALTY', 'UNAUTHORIZED_DUMP'", max_length=50)),
                ('c_ratio_logged', models.FloatField(default=1.0, help_text='Lifetime Empathy Ratio (C)')),
                ('e_batch_logged', models.FloatField(default=1.0, help_text='Local Batch Efficiency (E_batch)')),
                ('bonus_points_applied', models.FloatField(default=0.0, help_text='Scavenger/Rescue points (B)')),
                ('penalty_points_applied', models.FloatField(default=0.0, help_text='Deductions (P)')),
                ('old_score', models.FloatField()),
                ('new_score', models.FloatField()),
                ('calculation_details', models.TextField(blank=True, help_text='Human-readable breakdown of the math.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='couriers.deliverybatch')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='couriers.courier')),
            ],
        ),
    ]
