# Generated by Django 5.2.7 on 2026-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='paystack_recipient_code',
            field=models.CharField(help_text='RCP code from Paystack', max_length=100),
        ),
    ]
