# Generated by Django 5.2.7 on 2026-01-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0005_walletsecurity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer Personal'), ('VENDOR', 'Vendor Business'), ('COURIER', 'Courier Earnings')], default='CUSTOMER', max_length=20),
        ),
    ]
