# Generated by Django 5.2.7 on 2026-02-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0006_alter_wallet_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('PURCHASE_LOCK', 'Purchase (Escrow Lock)'), ('PURCHASE_RELEASE', 'Purchase (Vendor Credit)'), ('WITHDRAWAL', 'Withdrawal'), ('REFUND', 'Refund'), ('CREDIT', 'Credit')], max_length=20),
        ),
    ]
