# Generated by Django 5.2.7 on 2026-03-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0007_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer Personal'), ('VENDOR', 'Vendor Business'), ('COURIER', 'Courier Earnings'), ('COURIER_ADVANCE', 'Advance Payout account to get the food')], default='CUSTOMER', max_length=20),
        ),
    ]
