# Generated by Django 5.2.7 on 2026-04-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0008_alter_wallet_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer Personal'), ('VENDOR', 'Vendor Business'), ('COURIER', 'Courier Earnings'), ('COURIER_ADVANCE', 'Advance Payout account to get the food'), ('ADMIN', 'Admin (Platform)')], default='CUSTOMER', max_length=20),
        ),
    ]
